"""CyberRemesher Python bindings.

Thin, Pythonic ctypes bindings over the engine's versioned C ABI (the `capi`
module, ``libcyber_capi_shared``). Importing this package never loads the
shared library; that happens lazily on the first engine call, so the package
imports cleanly on a machine where the engine has not been built.

    from cyberremesh import Mesh, RemeshParams, remesh, CyberError

    mesh = Mesh.load("model.fbx")          # .obj .ply .stl .gltf .glb .fbx
    result = remesh(mesh, RemeshParams(target_quad_count=5000))
    print(result.stats.quads)
    result.subdivide(project_to=mesh)      # 4x the quads, back on the surface
    result.save("out.obj")                 # FBX is import-only
"""

from .api import (
    HANDOFF_VERSION,
    AtlasParams,
    UnwrapSeamsParams,
    AtlasResult,
    BakeMap,
    BakeParams,
    BentNormalSpace,
    DensityNormalization,
    EncodingBasis,
    IdColor,
    IDENTITY_PLACEMENT,
    ImageDensity,
    ImageEncoding,
    ImagePadding,
    ImageRegions,
    BakeProviderMap,
    BakeProviderResult,
    PaddingMode,
    UpAxis,
    BundleFile,
    BundleResult,
    UdimLayout,
    UdimRefusal,
    UdimTileBake,
    ConformReport,
    CyberError,
    Document,
    ExportPreset,
    FieldEvaluator,
    HandoffInfo,
    IncompatibleVersionError,
    UnsupportedTopologyError,
    Falloff,
    LoopSubdivideMode,
    HAVE_NUMPY,
    Image,
    IsotropicParams,
    Mesh,
    FlowGuide,
    RemeshParams,
    RemeshLimits,
    ZRemesherParams,
    ZRemesherReport,
    SymmetryDetectionReport,
    InjectabilityReport,
    SemanticBoundaryReport,
    SemanticBoundaryResult,
    SeamCostParams,
    SeamPath,
    SeamSet,
    PresetMapEntry,
    PartialRetopologyReport,
    SnapReport,
    Snapper,
    SoftTransformReport,
    Statistics,
    Subdivision,
    bake,
    bake_field,
    bake_udim,
    bake_regions,
    bake_provider_bake,
    bake_provider_map_list,
    bake_provider_maps,
    bake_provider_size,
    find_bake_provider_map,
    builtin_presets,
    conform,
    is_available,
    remesh,
    version,
    abi_version,
    max_import_vertices,
    max_import_input_bytes,
    max_import_faces,
    max_bake_pixels,
    seamless_solver,
    udim_tiles,
    set_max_import_vertices,
    set_max_import_input_bytes,
    set_max_import_faces,
    set_max_bake_pixels,
    check_abi,
    ABI_VERSION_MAJOR,
    ABI_VERSION_MINOR,
    CountPolicy,
    TargetCountReport,
    write_bundle,
    status_string,
    Snapper,
    SurfaceHit,
    VertexHit,
    RayHit,
    LoopMetrics,
    ContourReport,
    Symmetry,
    ResymmetrizeReport,
    LoopSlideReport,
)

# The gesture grammar. Kept in its own module because it is interpretation
# ONLY -- nothing here mutates a mesh -- and mixing it into the mutating API
# would blur exactly the line that lets a host preview a candidate before
# committing to it.
from . import strokes
from .strokes import (
    Candidate,
    ElementKind,
    Interpretation,
    StrokeAction,
    StrokeContext,
    StrokeShape,
    interpret,
)

__all__ = [
    "Mesh",
    "Document",
    "FlowGuide",
    "RemeshParams",
    "RemeshLimits",
    "ZRemesherParams",
    "ZRemesherReport",
    "SymmetryDetectionReport",
    "InjectabilityReport",
    "SemanticBoundaryReport",
    "SemanticBoundaryResult",
    "Statistics",
    "remesh",
    "CyberError",
    "is_available",
    "version",
    "abi_version",
    "max_import_vertices",
    "max_import_input_bytes",
    "max_import_faces",
    "max_bake_pixels",
    "seamless_solver",
    "set_max_import_vertices",
    "set_max_import_input_bytes",
    "set_max_import_faces",
    "set_max_bake_pixels",
    "check_abi",
    "ABI_VERSION_MAJOR",
    "ABI_VERSION_MINOR",
    "CountPolicy",
    "TargetCountReport",
    "status_string",
    "Snapper",
    "SurfaceHit",
    "VertexHit",
    "RayHit",
    "LoopMetrics",
    "ContourReport",
    "Symmetry",
    "ResymmetrizeReport",
    "LoopSlideReport",
    "strokes",
    "interpret",
    "Interpretation",
    "Candidate",
    "StrokeShape",
    "StrokeContext",
    "StrokeAction",
    "ElementKind",
    "HAVE_NUMPY",
    "BakeMap",
    "BakeParams",
    "BentNormalSpace",
    "DensityNormalization",
    "EncodingBasis",
    "IdColor",
    "IDENTITY_PLACEMENT",
    "ImageDensity",
    "ImageEncoding",
    "ImagePadding",
    "ImageRegions",
    "PaddingMode",
    "UpAxis",
    "Image",
    "bake",
    "bake_udim",
    "bake_regions",
    "udim_tiles",
    "AtlasParams",
    "IsotropicParams",
    "UnwrapSeamsParams",
    "AtlasResult",
    "Falloff",
    "SnapReport",
    "LoopSubdivideMode",
    "UnsupportedTopologyError",
    "Snapper",
    "SoftTransformReport",
    "PartialRetopologyReport",
    "Subdivision",
    "SeamCostParams",
    "SeamSet",
    "HandoffInfo",
    "HANDOFF_VERSION",
    "IncompatibleVersionError",
    "FieldEvaluator",
    "bake_field",
    "bake_provider_bake",
    "bake_provider_map_list",
    "bake_provider_maps",
    "bake_provider_size",
    "find_bake_provider_map",
    "BakeProviderMap",
    "BakeProviderResult",
    "ConformReport",
    "conform",
    "SeamPath",
    "builtin_presets",
    "ExportPreset",
    "PresetMapEntry",
    "BundleFile",
    "BundleResult",
    "UdimLayout",
    "UdimRefusal",
    "UdimTileBake",
    "write_bundle",
]
__version__ = "0.10.0"
